kind: Secret
apiVersion: v1
metadata:
  name: vault-example
type: Opaque
data:
  username: <path:mzc-spring/data/java_and_vault/dev#spring.datasource.username>
  password: <path:mzc-spring/data/java_and_vault/dev#spring.datasource.password>